### PR TITLE
Enable Hackage-friendly Stack.yaml settings

### PR DESCRIPTION
**Pull request by hvr**

### CODE REVIEW

**Comment by johannesgerer** [comment]
Thank you. Could provide material that explains what makes this change 

> Hackage-friendly

?

 `pvp-bounds: both` seems to restrict the allowed range of versions, but only when using stack, so I am confused...

**Comment by hvr** [comment]
@johannesgerer Unfortunately it's not automated, sometimes I'm a bit in a hurry and don't add more details rightaway; when I get notified about packages uploaded without any bounds that fail on the Hackage matrix builder (and our primary mission as Hackage Trustees/Curators is to make sure that `cabal install $PKG` doesn't run into compile failures), and I notice a stack.yaml file in its git repo, then I assume (which means I can be wrong sometimes) it was developed against a stackage snapshot and uploaded via stack as well. And adding `pvp-bounds: both` is usually the easiest way to help ensure that the next uploaded release complies with Hackage guidelines.

That being said, in your case it's a bit different than usual, as you use both `cabal` and `stack` apparently. Do you also compile with `cabal`, or do you only use `cabal sdist`?

**Comment by johannesgerer** [comment]
Thanks for clarifying things. I have just recently started to include `stack.yaml` files to my projects. I will merge and upload a new version with bounds.

**Comment by johannesgerer** [comment]
It still won't compile with cabal. It needs a not yet existing version of `hledger`. This seems only possible using `stack`.

**Pull request merged**
